name: build

on:
  push:
    branches: [master]
  workflow_call:

jobs:
  esp-elf-gcc:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        esp_idf_version: [latest, v5.5.1, v5.4.3, v5.3.4, v5.2.6]
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - uses: espressif/esp-idf-ci-action@v1.2.0
        with:
          path: examples/posix
          esp_idf_version: ${{ matrix.esp_idf_version }}
          target: esp32

  x86_64-linux-gnu-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt install -y '^libxcb.*-dev' libglu1-mesa-dev libx11-xcb-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxrender-dev ninja-build
      - run: cmake --preset "Release x86_64-linux-gnu-gcc"
      - run: cmake --build build --parallel --target Z21Sim
      - name: Find archive file
        run: |
          echo "ARTIFACT_NAME=$(find build -type f -name "Z21Sim-*.zip" -printf "%f\n")" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=$(find build -type f -name "Z21Sim-*.zip")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

  x86_64-w64-mingw32-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt install -y libz-mingw-w64 libz-mingw-w64-dev mingw-w64 ninja-build
          sudo pip install aqtinstall --break-system-packages --ignore-installed
      - run: cmake --preset "Release x86_64-w64-mingw32-gcc"
      - run: cmake --build build --parallel --target Z21Sim
      - name: Find archive file
        run: |
          echo "ARTIFACT_NAME=$(find build -type f -name "Z21Sim-*.zip" -printf "%f\n")" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=$(find build -type f -name "Z21Sim-*.zip")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
